### PR TITLE
fix(castmill): use utc_timestamps instead of native

### LINKED ISSUE #72: Use UTC timestamps in ecto
The default (and hence what we use today) is NaiveDateTime. Change this to UTC.

### PR DESCRIPTION
**Pull request by arokor**
Use utc_datetime everywhere in Ecto. In order to set this globally I created a custom Schema implementation with this setting and then used it everywhere. Resolves #72

### CODE REVIEW

File: packages/castmill/test/castmill/devices_test.exs [hunk 1]
```diff
@@ -166,11 +166,7 @@ defmodule Castmill.DevicesTest do
       assert {:error, _} = Devices.recover_device(device.hardware_id, device.last_ip)
 
       # Setting the updated_at to an hour ago
-      hour_ago =
-        :os.system_time(:seconds)
-        |> Kernel.-(3600)
-        |> DateTime.from_unix!(:second)
-        |> DateTime.to_naive()
+      hour_ago = DateTime.utc_now() |> DateTime.add(-1, :hour)
```
Comment (manast) [inline packages/castmill/test/castmill/devices_test.exs:169]: much simpler now!

**Review by manast — APPROVED** [review]
LGTM
